'use strict';
const $=id=>document.getElementById(id), KEY='haeseong-sports-league-v1', names=['A','B','C','D'], colors=['#ecc56a','#a7cee3','#d5b5e5','#a8d5a0'];
let state=League.reorder(League.fresh()),tab='volley',selected={volley:0,shoe:0},history=[],storageError=false;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!League.valid(parsed))throw Error();state=League.reorder(parsed);}}catch{storageError=true;}
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',3500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='● 이 기기에 자동 저장';}catch{$('saveStatus').textContent='⚠ 저장 실패 · 백업 필요';toast('기기 저장에 실패했습니다. 기록 백업을 내려받으세요.');}}
function ask(message,value){return new Promise(resolve=>{const d=document.createElement('dialog');d.className='app-dialog';const text=document.createElement('p');text.textContent=message;d.append(text);let input;if(value!==undefined){input=document.createElement('input');input.type='number';input.min='0';input.max='9999';input.value=value;d.append(input);}const actions=document.createElement('div');actions.className='actions';for(const [label,ok] of [['취소',false],['확인',true]]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{d.close();d.remove();resolve(ok?(input?input.value:true):(input?null:false));};actions.append(b);}d.append(actions);d.addEventListener('cancel',e=>{e.preventDefault();d.close();d.remove();resolve(input?null:false);});(document.fullscreenElement||document.body).append(d);d.showModal();if(input)input.focus();});}
function renderOutcome(m,isVolley,winner){
  const el=$('gameOutcome');el.className='game-outcome';el.hidden=false;
  if(isVolley&&!League.volleyScoreValid(m.x,m.y)){el.textContent='기존 점수 · 새 규칙(11점 / 최대 13점)에 맞게 수정하세요.';return;}
  if(winner){el.classList.add('won');el.textContent='🏆 '+names[winner==='x'?m.a:m.b]+'조 승리! · '+m.x+' : '+m.y;return;}
  if(!isVolley){el.hidden=true;return;}
  if(m.x>=10&&m.y>=10){el.classList.add('deuce');el.textContent=m.x===12&&m.y===12?'듀스 12 : 12 · 다음 1점으로 승리!':'듀스 · 2점 차 승리 / 13점 상한';}
  else el.textContent='11점 선취 · 듀스 있음 · 최대 13점';
}
function current(){return state.sports[tab][selected[tab]];}
function checkpoint(){history.push(JSON.stringify(state));if(history.length>50)history.shift();}
function table(rows){return `<table><thead><tr><th>순위</th><th>조</th><th>경기</th><th>승 / 무 / 패</th><th>득점</th><th>실점</th><th>득실</th><th>승점</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rank}</td><td><b>${names[r.team]}조</b></td><td>${r.played}</td><td>${r.win} / ${r.draw} / ${r.loss}</td><td>${r.for}</td><td>${r.against}</td><td>${r.diff>0?'+':''}${r.diff}</td><td>${r.points}</td></tr>`).join('')}</tbody></table>`;}
function overall(){const v=League.standings(state.sports.volley,state.rules),s=League.recordRows(state.shoeRecord);const rows=names.map((_,team)=>{const a=v.find(r=>r.team===team),b=s.find(r=>r.team===team);return{team,v:a.points,s:b.points,points:a.points+b.points,played:a.played};}).sort((a,b)=>b.points-a.points||a.team-b.team);rows.forEach((r,i)=>r.rank=i&&r.points===rows[i-1].points?rows[i-1].rank:i+1);return rows;}
function overallHTML(){return `<table><thead><tr><th>종합 순위</th><th>조</th><th>빅발리볼 경기</th><th>빅발리볼 승점</th><th>기록전 승점</th><th>승점 합계</th></tr></thead><tbody>${overall().map(r=>`<tr><td>${r.rank}</td><td><b>${names[r.team]}조</b></td><td>${r.played} / 3</td><td>${r.v}</td><td>${r.s}</td><td>${r.points}</td></tr>`).join('')}</tbody></table>`;}
function render(){const all=state.sports.volley,count=all.filter(m=>m.done).length,leaders=overall().filter(r=>r.rank===1).map(r=>names[r.team]+'조');$('stats').innerHTML=`<div class="stat"><small>참가 팀</small><strong>4<span>개 조</span></strong></div><div class="stat"><small>빅발리볼 완료</small><strong>${count}<span>/ 6 경기</span></strong></div><div class="stat"><small>신발던지기 기록</small><strong>${state.shoeRecord.values.filter(v=>v!==null).length}<span>/ 4개 조${state.shoeRecord.done?" · 확정":""}</span></strong></div><div class="stat"><small>종합 선두</small><strong style="font-size:${leaders.length>2?18:29}px">${count||state.shoeRecord.done?leaders.join(' · '):'—'}<span>${count||state.shoeRecord.done?'':'경기 대기'}</span></strong></div>`;
document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-pressed',b.dataset.tab===tab);});$('sportView').hidden=tab!=='volley';$('recordView').hidden=tab!=='shoe';$('overallView').hidden=tab!=='overall';$('settingsView').hidden=tab!=='settings';$('overallTable').innerHTML=overallHTML();if(tab==='settings'){for(const k of ['win','draw','loss'])$(k).value=state.rules[k];return;}if(tab==='overall')return;if(tab==='shoe'){renderRecord();return;}
const matches=state.sports[tab],m=current(),idx=selected[tab],isVolley=tab==='volley',winner=isVolley?League.volleyWinner(m.x,m.y):null;renderOutcome(m,isVolley,winner);$('sportTitle').textContent=isVolley?'빅발리볼 리그':'신발던지기 리그';$('sportCaption').textContent=isVolley?'BIG VOLLEYBALL LEAGUE':'SHOE TOSS LEAGUE';$('matchLabel').textContent=`${Math.floor(idx/2)+1}라운드 · ${idx+1}경기 ${m.done?' / 경기 확정':' / 점수 기록'}`;$('matchSelect').innerHTML=matches.map((m,i)=>`<option value="${i}" ${i===idx?'selected':''}>${i+1}경기 · ${names[m.a]}조 vs ${names[m.b]}조${m.done?' ✓':''}</option>`).join('');$('scoreTeams').innerHTML=['x','y'].map((side,i)=>`${i?'<div class="versus">VS</div>':''}<div><div class="team-label" style="--team:${colors[i?m.b:m.a]}"><i></i>${names[i?m.b:m.a]}조</div><button class="score" data-side="${side}" data-delta="1" aria-label="${names[i?m.b:m.a]}조 현재 ${m[side]}점, 1점 추가" ${m.done||winner?'disabled':''}>${m[side]}</button><div class="adjust"><button data-side="${side}" data-delta="-1" ${m.done||m[side]===0?'disabled':''}>− 1</button><button data-side="${side}" data-direct="true" ${m.done?'disabled':''}>점수 입력</button><button data-side="${side}" data-delta="1" ${m.done||winner?'disabled':''}>+ 1</button></div></div>`).join('');$('finish').disabled=isVolley&&!m.done&&!winner;$('finish').textContent=m.done?'확정 취소 · 결과 수정':'경기 종료 · 결과 확정';$('undo').disabled=!history.length;$('boardHint').textContent=m.done?'확정된 결과가 승점에 반영되었습니다.':isVolley?(winner?'승리! 결과를 확정하면 승점에 반영됩니다.':'11점 선취 · 10:10부터 2점 차 · 13점 먼저 도달하면 승리'):'조별 점수 합계를 입력한 뒤 결과를 확정하세요.';$('progress').textContent=`${matches.filter(m=>m.done).length} / 6 경기 완료`;$('schedule').innerHTML=matches.map((m,i)=>`<div class="match ${i===idx?'selected':''} ${m.done?'done':''}"><span class="round">${Math.floor(i/2)+1}R · ${i+1}</span><span class="teams">${names[m.a]}조 <span style="color:#a2aaa0;font-weight:400">vs</span> ${names[m.b]}조</span><span class="result">${m.done||m.x||m.y?`${m.x} : ${m.y}`:'— : —'}</span><button data-match="${i}">${m.done?'확정 ✓':i===idx?'선택됨':'경기 선택'}</button></div>`).join('');$('standings').innerHTML=table(League.standings(matches,state.rules));$('ruleSummary').textContent=`승리 ${state.rules.win}점 · 무승부 ${state.rules.draw}점 · 패배 ${state.rules.loss}점`;
}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',async()=>{tab=b.dataset.tab;render();}));$('matchSelect').addEventListener('change',e=>{selected[tab]=Number(e.target.value);render();});$('schedule').addEventListener('click',async e=>{const b=e.target.closest('[data-match]');if(b){selected[tab]=Number(b.dataset.match);render();}});
$('scoreTeams').addEventListener('click',async e=>{const b=e.target.closest('[data-side]');if(!b||b.disabled||current().done)return;const m=current(),side=b.dataset.side;if(tab==='volley'&&League.volleyWinner(m.x,m.y)&&b.dataset.delta==='1')return;let next=m[side]+Number(b.dataset.delta);if(b.dataset.direct){const input=await ask(tab==='volley'?'빅발리볼 점수를 입력하세요. (0~13 정수)':'조별 점수를 입력하세요. (0~9999 정수)',m[side]);if(input===null)return;if(!/^\d+$/.test(input.trim()))return toast('0~9999 사이의 정수를 입력하세요.');next=Number(input);}if(!Number.isInteger(next)||next<0||next>9999)return toast('점수는 0~9999까지 입력할 수 있습니다.');if(tab==='volley'&&!League.volleyScoreValid(side==='x'?next:m.x,side==='y'?next:m.y))return toast('11점 선취·듀스 13점 상한에 맞는 점수를 입력하세요.');checkpoint();m[side]=next;save();render();});
$('finish').addEventListener('click',async()=>{const m=current();if(tab==='volley'&&!m.done&&!League.volleyWinner(m.x,m.y))return toast('승리 점수에 도달한 후 결과를 확정하세요.');if(!await ask(m.done?'확정을 취소하고 수정할까요? 이 경기는 재확정 전까지 순위에서 제외됩니다.':`${names[m.a]}조 ${m.x} : ${m.y} ${names[m.b]}조\n${m.x===m.y?'무승부':names[m.x>m.y?m.a:m.b]+'조 승리'}로 확정할까요?`))return;checkpoint();m.done=!m.done;save();render();toast(m.done?'경기 결과와 승점을 반영했습니다.':'결과를 수정한 후 다시 확정하세요.');});
$('undo').addEventListener('click',async()=>{if(!history.length)return;state=JSON.parse(history.pop());save();render();toast('마지막 기록 변경을 되돌렸습니다.');});
$('settingsForm').addEventListener('submit',e=>{e.preventDefault();const rules=Object.fromEntries(['win','draw','loss'].map(k=>[k,Number($(k).value)]));if(Object.values(rules).some(n=>!Number.isInteger(n)||n<0||n>100))return toast('승점은 0~100 사이 정수로 입력하세요.');checkpoint();state.rules=rules;save();render();toast('승점 설정을 저장했습니다.');});
$('fullScreen').addEventListener('click',async()=>{try{await $('scoreboard').requestFullscreen();}catch{toast('이 브라우저에서는 전체 화면 기능을 지원하지 않습니다.');}});$('exitFull').addEventListener('click',async()=>document.exitFullscreen());
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('backup').addEventListener('click',async()=>download(JSON.stringify(state,null,2),'application/json','해성중-리그-백업.json'));
$('restore').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error();const data=JSON.parse(await file.text());if(!League.valid(data))throw Error();if(await ask('백업 파일의 기록으로 현재 기록을 교체할까요?')){checkpoint();state=League.reorder(data);save();render();toast('백업 기록을 불러왔습니다.');}}catch{toast('유효한 해성중 리그 백업 파일이 아닙니다.');}e.target.value='';});
$('reset').addEventListener('click',async()=>{if(await ask('두 종목의 모든 점수와 경기 결과를 초기화할까요? 필요한 기록은 먼저 백업하세요.')){checkpoint();state=League.reorder(League.fresh());save();render();toast('전체 기록을 초기화했습니다.');}});
$('csv').addEventListener('click',async()=>{const rows=[['해성중 전학공 스포츠클럽 역량강화 연수'],['종목','경기','조1','조2','점수1','점수2','상태']];for(const k of ['volley'])state.sports[k].forEach((m,i)=>rows.push([k==='volley'?'빅발리볼':'신발던지기',i+1,names[m.a]+'조',names[m.b]+'조',m.x,m.y,m.done?'확정':'미확정']));rows.push([],['신발던지기 기록전','조','기록','단위','순위','승점','상태']);League.recordRows(state.shoeRecord).forEach(r=>rows.push(['신발던지기',names[r.team]+'조',r.value??'',state.shoeRecord.unit,r.rank??'',r.points,state.shoeRecord.done?'확정':'미확정']));rows.push([],['종합순위','조','빅발리볼 승점','신발던지기 승점','승점 합계']);overall().forEach(r=>rows.push([r.rank,names[r.team]+'조',r.v,r.s,r.points]));download('\ufeff'+rows.map(r=>r.join(',')).join('\r\n'),'text/csv;charset=utf-8','해성중-리그-결과.csv');});
$('print').addEventListener('click',async()=>{$('printArea').innerHTML=`<h1>해성중 전학공 스포츠클럽 역량강화 연수</h1><p>승리 ${state.rules.win} · 무승부 ${state.rules.draw} · 패배 ${state.rules.loss}점</p>${['volley'].map(k=>`<section><h2>${k==='volley'?'빅발리볼':'신발던지기'}</h2><p>${state.sports[k].map((m,i)=>`${i+1}경기 ${names[m.a]}-${names[m.b]} ${m.x}:${m.y} (${m.done?'확정':'미확정'})`).join('　 /　 ')}</p>${table(League.standings(state.sports[k],state.rules))}</section>`).join('')}<section><h2>신발던지기 기록전 (${state.shoeRecord.done?'확정':'미확정'})</h2>${recordTable()}</section><section><h2>종합 순위</h2>${overallHTML()}</section>`;window.print();});
setupRecord();render();if(storageError){$('saveStatus').textContent='⚠ 기존 기록 읽기 실패';toast('기존 저장 기록을 읽지 못했습니다. 백업 파일을 확인하세요.');}



