(function(root){
  const pairs=[[2,3],[0,1],[0,2],[1,3],[0,3],[1,2]];
  function fresh(){return {version:1,rules:{win:3,draw:1,loss:0},sports:{volley:pairs.map(([a,b])=>({a,b,x:0,y:0,done:false})),shoe:pairs.map(([a,b])=>({a,b,x:0,y:0,done:false}))}};}
  function standings(matches,rules){const rows=[0,1,2,3].map(team=>({team,played:0,win:0,draw:0,loss:0,for:0,against:0,points:0}));for(const m of matches){if(!m.done)continue;for(const [team,x,y] of [[m.a,m.x,m.y],[m.b,m.y,m.x]]){const r=rows[team];r.played++;r.for+=x;r.against+=y;const result=x>y?'win':x===y?'draw':'loss';r[result]++;r.points+=rules[result];}}rows.forEach(r=>r.diff=r.for-r.against);rows.sort((a,b)=>b.points-a.points||b.diff-a.diff||b.for-a.for||a.team-b.team);rows.forEach((r,i)=>r.rank=i&&r.points===rows[i-1].points&&r.diff===rows[i-1].diff&&r.for===rows[i-1].for?rows[i-1].rank:i+1);return rows;}
  function valid(s){return s?.version===1&&['win','draw','loss'].every(k=>Number.isInteger(s.rules?.[k])&&s.rules[k]>=0&&s.rules[k]<=100)&&['volley','shoe'].every(k=>Array.isArray(s.sports?.[k])&&s.sports[k].length===6&&pairs.every(([a,b])=>s.sports[k].filter(m=>m?.a===a&&m?.b===b).length===1)&&s.sports[k].every(m=>typeof m.done==='boolean'&&[m.x,m.y].every(n=>Number.isInteger(n)&&n>=0&&n<=9999)));}
  function reorder(s){if(!valid(s))throw Error('Invalid league data');for(const k of ['volley','shoe'])s.sports[k]=pairs.map(([a,b])=>s.sports[k].find(m=>m.a===a&&m.b===b));return s;}
  function volleyScoreValid(x,y){const hi=Math.max(x,y),lo=Math.min(x,y);return [x,y].every(n=>Number.isInteger(n)&&n>=0&&n<=13)&&!(hi===13&&lo===13)&&(hi<=11||hi===12&&lo>=10||hi===13&&lo>=11);}
  function volleyWinner(x,y){if(!volleyScoreValid(x,y))return null;return Math.max(x,y)>=11&&(Math.abs(x-y)>=2||Math.max(x,y)===13)?(x>y?'x':'y'):null;}
  const api={fresh,standings,valid,reorder,volleyScoreValid,volleyWinner};if(typeof module!=='undefined')module.exports=api;else root.League=api;
})(typeof window!=='undefined'?window:globalThis);
